// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRequest struct {
	StartTime   int    `json:"startTime"`
	EndTime     int    `json:"endTime"`
	Description string `json:"description"`
}

type Period struct {
	ID          string `json:"id"`
	StartTime   int    `json:"startTime"`
	EndTime     int    `json:"endTime"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type Request struct {
	ID          string `json:"id"`
	StartTime   int    `json:"startTime"`
	EndTime     int    `json:"endTime"`
	Description string `json:"description"`
	Requester   *User  `json:"requester"`
	Requestee   *User  `json:"requestee"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}
